messages = {"Cantidad de jugadores": "Hoy ha sido uno de esos días en los que la soledad se siente más pesada. Decidí buscar un juego para distraerme un poco, pero me encontré con que todos los juegos que tengo son para dos jugadores. Es frustrante ver cómo cada caja me recuerda que no tengo a nadie con quien compartir estos momentos. Me siento atrapada, no solo por la vegetación tóxica que rodea mi casa, sino también por esta sensación de aislamiento. A veces, solo quiero reírme con alguien, competir en un juego de mesa o simplemente tener una conversación cara a cara. Pero aquí estoy, rodeada de juegos que no puedo jugar sola. Supongo que tendré que ser creativa y encontrar una manera de adaptarlos para jugar sola, o tal vez inventar mis propias reglas. Pero hoy, solo necesitaba desahogarme y expresar lo mucho que extraño la compañía humana.",
            "Huele de maravilla": "Hoy, mientras preparaba mi desayuno, me sorprendí al darme cuenta de lo afortunada que soy de poder disfrutar de una comida caliente. Después de tantos días encerrada, rodeada de vegetación tóxica, cada pequeño placer se siente como un lujo. El aroma del café recién hecho llenó la cocina, y el calor de la taza en mis manos me reconfortó más de lo que puedo expresar. Preparar unas tostadas crujientes y unos huevos revueltos me hizo sentir un poco más normal, como si por un momento, todo estuviera bien en el mundo. Es increíble cómo algo tan simple como un desayuno caliente puede levantarme el ánimo y darme fuerzas para enfrentar otro día en este encierro. A veces, es fácil olvidar las pequeñas cosas que nos traen alegría, pero hoy, estoy agradecida por este pequeño momento de paz y normalidad.",
            "AUCHH": "El fuego quema, ten cuidado."}

def get_message(tittle):
    global messages
    if tittle in messages:
        return messages[tittle]
    else:
        return "No se encontró el mensaje."