messages = {"Cantidad de jugadores": "Hoy ha sido uno de esos días en los que la soledad se siente más pesada. Decidí buscar un juego para distraerme un poco, pero me encontré con que todos los juegos que tengo son para dos jugadores. Es frustrante ver cómo cada caja me recuerda que no tengo a nadie con quien compartir estos momentos. Me siento atrapada, no solo por la vegetación tóxica que rodea mi casa, sino también por esta sensación de aislamiento. A veces, solo quiero reírme con alguien, competir en un juego de mesa o simplemente tener una conversación cara a cara. Pero aquí estoy, rodeada de juegos que no puedo jugar sola. Supongo que tendré que ser creativa y encontrar una manera de adaptarlos para jugar sola, o tal vez inventar mis propias reglas. Pero hoy, solo necesitaba desahogarme y expresar lo mucho que extraño la compañía humana.",
            "Huele de maravilla": "Hoy, mientras preparaba mi desayuno, me sorprendí al darme cuenta de lo afortunada que soy de poder disfrutar de una comida caliente. Después de tantos días encerrada, rodeada de vegetación tóxica, cada pequeño placer se siente como un lujo. El aroma del café recién hecho llenó la cocina, y el calor de la taza en mis manos me reconfortó más de lo que puedo expresar. Preparar unas tostadas crujientes y unos huevos revueltos me hizo sentir un poco más normal, como si por un momento, todo estuviera bien en el mundo. Es increíble cómo algo tan simple como un desayuno caliente puede levantarme el ánimo y darme fuerzas para enfrentar otro día en este encierro. A veces, es fácil olvidar las pequeñas cosas que nos traen alegría, pero hoy, estoy agradecida por este pequeño momento de paz y normalidad.",
            "AUCHH": "El fuego quema, ten cuidado.",
            "AyAyayYy": "Tengo que dejar de pincharme con esta botella. ¿Por qué habrá tantas botellas?",
            "El Principito – Capítulo 1": "Cuando yo tenía seis años vi en un libro sobre la selva virgen que se titulaba “Historias vividas”, una magnífica lámina. Representaba una serpiente boa que se tragaba a una fiera. Esta es la copia del dibujo. En el libro decía: “Las serpientes boas se tragan su presas enteras, sin masticarlas. Luego no pueden moverse y duermen durante los seis meses que dura su digestión”. Reflexioné mucho en ese momento sobre las aventuras de la jungla y a mi vez logré trazar con un lápiz de colores mi primer dibujo. Mi dibujo número 1. Era asi: Enseñé mi obra de arte a las personas mayores y les pregunté si mi dibujo les asustaba.-¿Por qué habría de asustar un sombrero? – me respondieron. Mi dibujo no representaba un sombrero. Representaba una serpiente boa que digería un elefante. Dibujé entonces el interior de la serpiente boa a fin de que las personas grandes pudieran comprender. Siempre necesitan explicaciones. Mi dibujo número 2 era así: Las personas grandes  me aconsejaron que dejara a un lado los dibujos de serpientes boas abiertas o cerradas, y que me interesara un poco más en la geografía, la historia, el cálculo y la gramática. Asi fue cómo, a la edad de seis años abandoné una magnífica carrera de pintor. Había quedado desilusionado por el fracaso de mis dibujos número 1 y número 2. Las personas grandes nunca comprenden nada por sí solas y es muy aburrido para los niños tener que darles una y otra vez explicaciones. Tuve, pues, que elegir otro oficio y aprendí a pilotear aviones. He volado un poco por todo el mundo y la geografía, en efecto, me ha servido de mucho; al primer vistazo podía distinguir perfectamente la China de Arizona. Esto es muy útil, sobre todo si se pierde uno durante la noche. A lo largo de mi vida he tenido multitud de contactos con multitud de gente seria. Viví mucho con personas grandes. Las he conocido muy de cerca; pero esto no ha mejorado demasiado mi opinión sobre ellas. Cuando me he encontrado con alguien que me parecía un poco lúcido, lo he sometido a la experiencia de mi dibujo número 1 que he conservado siempre. Quería saber si verdaderamente era un ser comprensivo. Pero siempre me respondian:: “Es un sombrero”. Entonces no le hablaba ni de serpientes boas, ni de la selva virgen y ni de estrellas. Poniéndome a su altura, les hablaba del bridge, del golf, de política y de corbatas. Y la persona grande se quedaba muy contento de conocer a un hombre tan razonable.",
            "Que pena de vista": "Hoy me acerqué a la ventana y miré hacia el jardín. Lo que una vez fue un lugar lleno de vida y color, ahora está muerto y lleno de tierra envenenada. Mis frutales favoritos, que solían alegrar mis días con sus vibrantes colores, están marchitos y muertos.La vista me llenó de una profunda nostalgia y tristeza. Recuerdo los días en que solía pasar horas cuidando de mis plantas, sintiendo la tierra entre mis dedos y viendo cómo crecían y florecían. Ahora, todo eso parece un sueño lejano, casi irreal.Es difícil aceptar cómo ha cambiado todo tan drásticamente. Me siento atrapada, no solo físicamente, sino también emocionalmente, en un mundo que ya no reconozco. Escribo estas palabras con la esperanza de liberar un poco de esta tristeza que llevo dentro, de encontrar algún consuelo en expresar lo que siento.Echo de menos esos días simples y felices en el jardín, y aunque sé que no puedo volver atrás, escribir sobre ello me ayuda a mantener viva la memoria de lo que una vez fue.",
            "Nada": "Nada"}

def get_message(tittle):
    global messages
    if tittle in messages:
        return messages[tittle]
    else:
        return "No se encontró el mensaje."